# Telco Customer Churn — Data Cleaning

## Objective

The goal of this notebook is to clean and prepare the Telco Customer Churn dataset before analysis.

This notebook focuses on:

- loading the dataset
- inspecting its structure
- identifying missing values and data quality issues
- correcting data types
- creating cleaned variables for later analysis

A clean dataset is essential to ensure accurate business, financial, SQL, and predictive analysis.

In [1]:
import pandas as pd
import numpy as np

## Load Dataset

We begin by loading the Telco Customer Churn dataset.

In [2]:
df = pd.read_csv("../data/Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Dataset Shape

We first check the number of rows and columns in the dataset.

In [3]:
print("Dataset shape:", df.shape)

Dataset shape: (7043, 21)

## Column Names

We list all columns to understand the dataset structure.

In [4]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

## Data Types and General Structure

We inspect data types and non-null counts to identify possible cleaning needs.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

## Sample of the Dataset

We review a small sample of rows to better understand the values stored in each column.

In [6]:
df.sample(5, random_state=42)

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
185,1024-GUALD,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,24.80,24.8,Yes
2715,0484-JPBRU,Male,0,No,No,41,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,Yes,Bank transfer (automatic),25.25,996.45,No
3825,3620-EHIMZ,Female,0,Yes,Yes,52,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.35,1031.7,No
1807,6910-HADCM,Female,0,No,No,1,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,No,Electronic check,76.35,76.35,Yes
132,8587-XYZSF,Male,0,No,No,67,Yes,No,DSL,No,...,No,Yes,No,No,Two year,No,Bank transfer (automatic),50.55,3260.1,No

## Check for Duplicate Rows

Duplicate rows can distort analysis, so we verify whether any complete duplicates exist.

In [7]:
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 0

## Remove Duplicate Rows if Needed

If duplicates exist, they should be removed. Otherwise, the dataset remains unchanged.

In [8]:
df = df.drop_duplicates().copy()
print("Dataset shape after duplicate check:", df.shape)

Dataset shape after duplicate check: (7043, 21)

## Missing Values

We check for missing values across all columns.

In [9]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

## Check for Blank Strings

In some datasets, missing values are stored as blank spaces instead of true null values.

This is especially important for the `TotalCharges` column in this dataset.

In [10]:
blank_strings = (df == " ").sum()
blank_strings[blank_strings > 0]

TotalCharges    11
dtype: int64

## Investigate TotalCharges

The `TotalCharges` column should be numeric, but in this dataset some rows contain blank strings.

These rows often correspond to very new customers with little or no billing history.

In [11]:
df[df["TotalCharges"] == " "].head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,,No

## Convert TotalCharges to Numeric

We convert `TotalCharges` to numeric format.

Invalid values are turned into missing values using `errors='coerce'`.

In [12]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")
df["TotalCharges"].head()

0      29.85
1    1889.50
2     108.15
3    1840.75
4     151.65
Name: TotalCharges, dtype: float64

## Missing Values After Conversion

After converting `TotalCharges`, we check how many missing values were created.

In [13]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

## Remove Rows with Missing TotalCharges

Because only a small number of rows are affected, we remove them to keep the dataset clean and consistent for later analysis.

In [14]:
rows_before = len(df)

df = df.dropna(subset=["TotalCharges"]).copy()

rows_after = len(df)
rows_removed = rows_before - rows_after

print("Rows before cleaning:", rows_before)
print("Rows after cleaning:", rows_after)
print("Rows removed:", rows_removed)

Rows before cleaning: 7043
Rows after cleaning: 7032
Rows removed: 11

## Final Missing Value Check

We confirm that the dataset no longer contains missing values.

In [15]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

## Review Unique Values in Categorical Columns

Before analysis, it is useful to understand the categories present in the dataset.

In [16]:
categorical_cols = df.select_dtypes(include="object").columns.tolist()
categorical_cols

['customerID',
 'gender',
 'Partner',
 'Dependents',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'Churn']

In [17]:
for col in categorical_cols:
    print(f"\n{col}")
    print(df[col].unique())

customerID
['7590-VHVEG' '5575-GNVDE' '3668-QPYBK' ... '4801-JZAZL' '8361-LTMKD'
 '3186-AJIEK']

gender
['Female' 'Male']

Partner
['Yes' 'No']

Dependents
['No' 'Yes']

PhoneService
['No' 'Yes']

MultipleLines
['No phone service' 'No' 'Yes']

InternetService
['DSL' 'Fiber optic' 'No']

OnlineSecurity
['No' 'Yes' 'No internet service']

OnlineBackup
['Yes' 'No' 'No internet service']

DeviceProtection
['No' 'Yes' 'No internet service']

TechSupport
['No' 'Yes' 'No internet service']

StreamingTV
['No' 'Yes' 'No internet service']

StreamingMovies
['No' 'Yes' 'No internet service']

Contract
['Month-to-month' 'One year' 'Two year']

PaperlessBilling
['Yes' 'No']

PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']

Churn
['No' 'Yes']

## Standardize Churn Variable

To make the dataset easier to use in analysis and modeling, we create a binary churn flag:

- `Yes` → 1
- `No` → 0

In [18]:
df["Churn_Flag"] = df["Churn"].map({"Yes": 1, "No": 0})
df[["Churn", "Churn_Flag"]].head()

  Churn  Churn_Flag
0    No           0
1    No           0
2   Yes           1
3    No           0
4   Yes           1

## Create Tenure Groups

Customer tenure is easier to analyze when grouped into broader lifecycle categories.

In [19]:
df["TenureGroup"] = pd.cut(
    df["tenure"],
    bins=[0, 12, 24, 48, 72],
    labels=["0-12 months", "13-24 months", "25-48 months", "49-72 months"],
    include_lowest=True
)

df[["tenure", "TenureGroup"]].head()

   tenure   TenureGroup
0       1   0-12 months
1      34  25-48 months
2       2   0-12 months
3      45  25-48 months
4       2   0-12 months

## Create Monthly Charges Groups

We group monthly charges into quartiles to simplify pricing analysis later.

In [20]:
df["MonthlyChargesGroup"] = pd.qcut(
    df["MonthlyCharges"],
    q=4,
    labels=["Low", "Medium", "High", "Very High"]
)

df[["MonthlyCharges", "MonthlyChargesGroup"]].head()

   MonthlyCharges MonthlyChargesGroup
0           29.85                 Low
1           56.95              Medium
2           53.85              Medium
3           42.30              Medium
4           70.70                High

## Validate New Columns

We verify that the engineered columns were created correctly.

In [21]:
df[["Churn", "Churn_Flag", "tenure", "TenureGroup", "MonthlyCharges", "MonthlyChargesGroup"]].head(10)

  Churn  Churn_Flag  tenure   TenureGroup  MonthlyCharges MonthlyChargesGroup
0    No           0       1   0-12 months           29.85                 Low
1    No           0      34  25-48 months           56.95              Medium
2   Yes           1       2   0-12 months           53.85              Medium
3    No           0      45  25-48 months           42.30              Medium
4   Yes           1       2   0-12 months           70.70                High
5   Yes           1       8   0-12 months           99.65           Very High
6    No           0      22  13-24 months           89.10                High
7    No           0      10   0-12 months           29.75                 Low
8   Yes           1      28  25-48 months          104.80           Very High
9    No           0      62  49-72 months           56.15              Medium

## Summary Statistics for Numeric Variables

We review descriptive statistics for the main numeric variables.

In [22]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges  TotalCharges   Churn_Flag
count    7032.000000  7032.000000     7032.000000   7032.000000  7032.000000
mean        0.162400    32.421786       64.798208   2283.300441     0.265785
std         0.368844    24.545260       30.085974   2266.771362     0.441782
min         0.000000     1.000000       18.250000     18.800000     0.000000
25%         0.000000     9.000000       35.587500    401.450000     0.000000
50%         0.000000    29.000000       70.350000   1397.475000     0.000000
75%         0.000000    55.000000       89.862500   3794.737500     1.000000
max         1.000000    72.000000      118.750000   8684.800000     1.000000

## Final Data Types

We confirm the final structure of the cleaned dataset.

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 24 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   customerID           7032 non-null   object
 1   gender               7032 non-null   object
 2   SeniorCitizen        7032 non-null   int64
 3   Partner              7032 non-null   object
 4   Dependents           7032 non-null   object
 5   tenure               7032 non-null   int64
 6   PhoneService         7032 non-null   object
 7   MultipleLines        7032 non-null   object
 8   InternetService      7032 non-null   object
 9   OnlineSecurity       7032 non-null   object
 10  OnlineBackup         7032 non-null   object
 11  DeviceProtection     7032 non-null   object
 12  TechSupport          7032 non-null   object
 13  StreamingTV          7032 non-null   object
 14  StreamingMovies      7032 non-null   object
 15  Contract             7032 non-null   object
 16  PaperlessBilling     7032 non-null   object
 17  PaymentMethod        7032 non-null   object
 18  MonthlyCharges       7032 non-null   float64
 19  TotalCharges         7032 non-null   float64
 20  Churn                7032 non-null   object
 21  Churn_Flag           7032 non-null   int64
 22  TenureGroup          7032 non-null   category
 23  MonthlyChargesGroup  7032 non-null   category
dtypes: category(2), float64(2), int64(3), object(17)
memory usage: 1.2+ MB

## Cleaned Dataset Preview

We display the cleaned dataset after all transformations.

In [24]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,Churn_Flag,TenureGroup,MonthlyChargesGroup
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,0,0-12 months,Low
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,No,One year,No,Mailed check,56.95,1889.50,No,0,25-48 months,Medium
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0-12 months,Medium
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0,25-48 months,Medium
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,0-12 months,High

## Save Cleaned Dataset

To keep the workflow organized, we save the cleaned version of the dataset for use in later notebooks.

In [25]:
df.to_csv("../data/telco_churn_cleaned.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

## Cleaning Summary

The dataset preparation process included:

- checking dataset size and structure
- verifying duplicates
- identifying blank values in `TotalCharges`
- converting `TotalCharges` to numeric format
- removing rows with missing `TotalCharges`
- creating new analytical variables:
  - `Churn_Flag`
  - `TenureGroup`
  - `MonthlyChargesGroup`

The dataset is now ready for exploratory, business, financial, SQL, and predictive analysis.

## Conclusion

The main data quality issue in this dataset was the presence of blank values in `TotalCharges`, which prevented the column from being treated as numeric.

After cleaning and feature engineering, the dataset is now structured and reliable for downstream analysis.

The next step is exploratory data analysis to better understand distributions, customer profiles, and churn patterns.